server:
  # 端口号和项目名
  port: 8088
  context-path: /springboot
  # 配置视图解析器
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 456789
  # 指定mapper文件路径
mybatis-plus:
  mapper-locations: classpath:com/maisel/dao/*Mapper.xml