
server:
  context-path: /springboot
  port: 8089
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 456789
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
    mapper-locations: classpath:com/maisel/springboot/dao/*Mapper.xml